Refatoração do menu vertical
fga-eps-mds/2022-2-EuPescador-Web pull request #19
Opened 2022-12-22 23:13 UTC by marcelog5

Co-authored-by: ServidioEC <dudaservidio@gmail.com>

2022-12-23 00:08 UTC, emysdias commented
Deve ser ajustado o sonarcloud que deu falha

2023-01-02 22:24 UTC, emysdias requested changes
![Screenshot from 2023-01-02 19-23-37](https://user-images.githubusercontent.com/52640974/210281761-57d8122c-48fd-4fbe-b2ea-b4fabd206c18.png)
a sidebar ta assim pra mim

2023-01-03 18:49 UTC, flyerjohn commented
Como conversado com o autor do pr, o @marcelog5, ainda falta testar as mudanças propostas

2023-01-06 00:19 UTC, emysdias requested changes
eu ia aceitar mas parece q ta alterando o estilo da página, olha a diferença do mapa para com o novo menu e o antigo

![Screenshot from 2023-01-05 21-15-43](https://user-images.githubusercontent.com/52640974/210904526-07ae4c33-8138-4336-bb43-5059fe7f7400.png)
![Screenshot from 2023-01-05 21-18-10](https://user-images.githubusercontent.com/52640974/210904529-d33246c8-ed61-4336-9f3b-dd2529f48387.png)

ai quando vou alternando de página a header fica se mexendo, tem como dar uma olhada se não ta afetando o estilo das outras páginas?

2023-01-06 03:01 UTC, marcelog5 commented
Resolvido @emysdias!

2023-01-06 17:55 UTC, emysdias approved these changes
showww, depois a gente ve pq ta quebrando o deploy

2023-01-06 17:55 UTC, merged